pipeline = [
  {
    $set: {
      // Basic customer information with extensive details
      customer_id: fakeNumber(15),
      account_number: fakePaddedNumberAsText(16),
      legacy_account_numbers: fakeListOfSubDocs(3, [
        fakePaddedNumberAsText(12),
      ]),
      created_date: fakeDateBeforeNow(10 * 365 * 24 * 60 * 60 * 1000), // Up to 10 years ago
      last_updated: fakeDateBeforeNow(12 * 60 * 60 * 1000), // Up to 12 hours ago
      status: fakeValueFromList([
        "ACTIVE",
        "INACTIVE",
        "SUSPENDED",
        "PENDING_VERIFICATION",
        "CLOSED",
        "FROZEN",
        "UNDER_REVIEW",
      ]),
      priority_level: fakeValueFromList([
        "PLATINUM_ELITE",
        "PLATINUM",
        "GOLD_PLUS",
        "GOLD",
        "SILVER_PLUS",
        "SILVER",
        "BRONZE",
        "STANDARD",
      ]),
      customer_segment: fakeValueFromList([
        "ULTRA_HIGH_NET_WORTH",
        "HIGH_NET_WORTH",
        "AFFLUENT",
        "MASS_AFFLUENT",
        "RETAIL",
        "BASIC",
      ]),
      relationship_manager: fakeFirstAndLastName(),
      branch_code: fakePaddedNumberAsText(6),
      region: fakeValueFromList([
        "NORTH_AMERICA",
        "EUROPE",
        "ASIA_PACIFIC",
        "LATIN_AMERICA",
        "MIDDLE_EAST_AFRICA",
      ]),

      // Comprehensive personal information with extensive details
      personal_info: {
        first_name: fakeFirstName(),
        last_name: fakeLastName(),
        middle_name: fakeFirstName(),
        full_name: fakeFirstAndLastName(),
        maiden_name: fakeLastName(),
        previous_names: fakeListOfSubDocs(2, [fakeFirstAndLastName()]),
        preferred_name: fakeFirstName(),
        title: fakeValueFromList([
          "Mr.",
          "Mrs.",
          "Ms.",
          "Dr.",
          "Prof.",
          "Rev.",
          "Hon.",
        ]),
        suffix: fakeValueFromList([
          "Jr.",
          "Sr.",
          "II",
          "III",
          "IV",
          "PhD",
          "MD",
          "Esq.",
        ]),
        date_of_birth: fakeDateBeforeNow(90 * 365 * 24 * 60 * 60 * 1000),
        place_of_birth: { $concat: [fakeTownName(), ", ", fakeCountryName()] },
        nationality: fakeCountryName(),
        citizenship: fakeListOfSubDocs(2, [fakeCountryName()]),
        ssn: fakePaddedNumberAsText(9),
        tax_id: fakePaddedNumberAsText(10),
        passport_number: fakePaddedNumberAsText(9),
        passport_country: fakeCountryName(),
        passport_expiry: fakeDateAfterNow(2 * 365 * 24 * 60 * 60 * 1000),
        drivers_license: fakePaddedNumberAsText(8),
        drivers_license_state: fakeValueFromList([
          "CA",
          "NY",
          "TX",
          "FL",
          "IL",
        ]),
        drivers_license_expiry: fakeDateAfterNow(4 * 365 * 24 * 60 * 60 * 1000),
        phone_primary: fakePaddedNumberAsText(10),
        phone_secondary: fakePaddedNumberAsText(10),
        phone_work: fakePaddedNumberAsText(10),
        phone_mobile: fakePaddedNumberAsText(10),
        phone_fax: fakePaddedNumberAsText(10),
        email_primary: fakeEmailAddress(15),
        email_secondary: fakeEmailAddress(12),
        email_work: fakeEmailAddress(18),
        email_personal: fakeEmailAddress(10),
        preferred_contact: fakeValueFromList([
          "EMAIL",
          "PHONE",
          "MAIL",
          "SMS",
          "SECURE_MESSAGE",
          "VIDEO_CALL",
        ]),
        language_preference: fakeValueFromList([
          "EN",
          "ES",
          "FR",
          "DE",
          "IT",
          "PT",
          "ZH",
          "JA",
          "KO",
          "AR",
          "RU",
          "HI",
          "NL",
          "SV",
          "NO",
        ]),
        secondary_languages: fakeListOfSubDocs(3, [
          "ES",
          "FR",
          "DE",
          "IT",
          "PT",
          "ZH",
          "JA",
          "KO",
          "AR",
          "RU",
          "HI",
        ]),
        marital_status: fakeValueFromList([
          "SINGLE",
          "MARRIED",
          "DIVORCED",
          "WIDOWED",
          "SEPARATED",
          "DOMESTIC_PARTNERSHIP",
          "CIVIL_UNION",
        ]),
        spouse_name: fakeFirstAndLastName(),
        dependents: fakeNumberBounded(0, 8),
        dependent_details: fakeListOfSubDocs(3, [
          {
            name: fakeFirstAndLastName(),
            relationship: fakeValueFromList([
              "CHILD",
              "STEPCHILD",
              "PARENT",
              "GRANDPARENT",
              "SIBLING",
              "OTHER",
            ]),
            age: fakeNumberBounded(0, 85),
            dependent_type: fakeValueFromList([
              "TAX_DEPENDENT",
              "BENEFICIARY",
              "EMERGENCY_CONTACT",
            ]),
          },
        ]),
        education_level: fakeValueFromList([
          "HIGH_SCHOOL",
          "ASSOCIATES",
          "BACHELORS",
          "MASTERS",
          "DOCTORATE",
          "PROFESSIONAL",
          "POST_DOCTORATE",
        ]),
        education_details: [
          {
            institution: fakeCompanyName(),
            degree: fakeValueFromList([
              "Bachelor of Science",
              "Master of Business Administration",
              "Doctor of Philosophy",
              "Juris Doctor",
            ]),
            field_of_study: fakeValueFromList([
              "Computer Science",
              "Business Administration",
              "Engineering",
              "Medicine",
              "Law",
              "Finance",
              "Marketing",
            ]),
            graduation_year: fakeNumberBounded(1980, 2024),
            gpa: fakeDecimalSignificantPlaces(2),
          },
        ],
        military_service: {
          served: fakeBoolean(),
          branch: fakeValueFromList([
            "ARMY",
            "NAVY",
            "AIR_FORCE",
            "MARINES",
            "COAST_GUARD",
            "SPACE_FORCE",
          ]),
          rank: fakeValueFromList([
            "ENLISTED",
            "NCO",
            "WARRANT_OFFICER",
            "OFFICER",
          ]),
          service_years: fakeNumberBounded(2, 30),
          veteran_status: fakeBoolean(),
        },
      },

      // Multiple addresses with comprehensive details
      addresses: [
        {
          type: "PRIMARY",
          street_number: fakeNumberBounded(1, 999999),
          street_name: fakeStreetName(),
          apartment: {
            $concat: ["Apt ", { $toString: fakeNumberBounded(1, 99999) }],
          },
          building: { $concat: ["Building ", fakeNAnyUpperChars(1)] },
          floor: fakeNumberBounded(1, 50),
          city: fakeTownName(),
          county: fakeTownName(),
          state: fakeValueFromList([
            "CA",
            "NY",
            "TX",
            "FL",
            "IL",
            "PA",
            "OH",
            "GA",
            "NC",
            "MI",
            "NJ",
            "VA",
            "WA",
            "AZ",
            "MA",
          ]),
          zip_code: fakeZipCode(),
          zip_plus_four: fakeNumber(4),
          country: fakeCountryName(),
          country_code: fakeValueFromList([
            "US",
            "CA",
            "GB",
            "DE",
            "FR",
            "AU",
            "JP",
            "SG",
          ]),
          coordinates: fakeLocationWithCoordinates(),
          verified: fakeBoolean(),
          verification_date: fakeDateBeforeNow(365 * 24 * 60 * 60 * 1000),
          verification_method: fakeValueFromList([
            "POSTAL_SERVICE",
            "UTILITY_BILL",
            "BANK_STATEMENT",
            "GOVERNMENT_ID",
          ]),
          residence_type: fakeValueFromList([
            "OWNED",
            "RENTED",
            "FAMILY",
            "CORPORATE",
            "TEMPORARY",
            "OTHER",
          ]),
          years_at_address: fakeNumberBounded(0, 40),
          property_value: fakeMoneyAmountDecimal(6),
          monthly_payment: fakeMoneyAmountDecimal(4),
          property_tax: fakeMoneyAmountDecimal(4),
          insurance_cost: fakeMoneyAmountDecimal(3),
        },
        {
          type: "BILLING",
          street_number: fakeNumberBounded(1, 999999),
          street_name: fakeStreetName(),
          city: fakeTownName(),
          state: fakeValueFromList(["CA", "NY", "TX", "FL", "IL"]),
          zip_code: fakeZipCode(),
          country: fakeCountryName(),
          verified: fakeBoolean(),
          same_as_primary: fakeBoolean(),
        },
        {
          type: "MAILING",
          street_number: fakeNumberBounded(1, 999999),
          street_name: fakeStreetName(),
          po_box: {
            $concat: ["PO Box ", { $toString: fakeNumberBounded(1, 99999) }],
          },
          city: fakeTownName(),
          state: fakeValueFromList(["WA", "OR", "NV", "AZ", "UT"]),
          zip_code: fakeZipCode(),
          country: fakeCountryName(),
          verified: fakeBoolean(),
          forwarding_service: fakeBoolean(),
        },
        {
          type: "WORK",
          company_name: fakeCompanyName(),
          street_number: fakeNumberBounded(1, 999999),
          street_name: fakeStreetName(),
          suite: {
            $concat: ["Suite ", { $toString: fakeNumberBounded(100, 99999) }],
          },
          city: fakeTownName(),
          state: fakeValueFromList(["CA", "NY", "TX", "FL", "IL"]),
          zip_code: fakeZipCode(),
          country: fakeCountryName(),
          phone: fakePaddedNumberAsText(10),
          extension: fakeNumber(4),
        },
        {
          type: "PREVIOUS",
          street_number: fakeNumberBounded(1, 999999),
          street_name: fakeStreetName(),
          city: fakeTownName(),
          state: fakeValueFromList(["CO", "NM", "WY", "MT", "ID"]),
          zip_code: fakeZipCode(),
          country: fakeCountryName(),
          years_at_address: fakeNumberBounded(1, 15),
          move_out_date: fakeDateBeforeNow(2 * 365 * 24 * 60 * 60 * 1000),
          reason_for_move: fakeValueFromList([
            "JOB_RELOCATION",
            "FAMILY",
            "UPGRADE",
            "DOWNSIZE",
            "FINANCIAL",
            "OTHER",
          ]),
        },
        {
          type: "VACATION",
          property_name: {
            $concat: [
              fakeTownName(),
              " ",
              fakeValueFromList([
                "Beach House",
                "Mountain Cabin",
                "Lake House",
                "Condo",
              ]),
            ],
          },
          street_number: fakeNumberBounded(1, 999999),
          street_name: fakeStreetName(),
          city: fakeTownName(),
          state: fakeValueFromList(["FL", "CA", "CO", "VT", "ME"]),
          zip_code: fakeZipCode(),
          country: fakeCountryName(),
          property_value: fakeMoneyAmountDecimal(6),
          usage_frequency: fakeValueFromList([
            "WEEKLY",
            "MONTHLY",
            "SEASONAL",
            "OCCASIONAL",
          ]),
        },
      ],

      // Comprehensive employment information with extensive history
      employment: {
        status: fakeValueFromList([
          "EMPLOYED",
          "UNEMPLOYED",
          "SELF_EMPLOYED",
          "RETIRED",
          "STUDENT",
          "DISABLED",
          "CONTRACTOR",
          "CONSULTANT",
          "ENTREPRENEUR",
        ]),
        company_name: fakeCompanyName(),
        company_size: fakeValueFromList([
          "STARTUP",
          "SMALL",
          "MEDIUM",
          "LARGE",
          "ENTERPRISE",
          "FORTUNE_500",
        ]),
        company_industry: fakeValueFromList([
          "Technology",
          "Healthcare",
          "Finance",
          "Education",
          "Manufacturing",
          "Retail",
          "Construction",
          "Transportation",
          "Government",
          "Non-profit",
          "Entertainment",
          "Agriculture",
          "Energy",
          "Real Estate",
          "Legal",
          "Consulting",
          "Media",
          "Hospitality",
          "Automotive",
          "Aerospace",
          "Biotechnology",
          "Telecommunications",
        ]),
        job_title: fakeValueFromList([
          "Chief Executive Officer",
          "Chief Technology Officer",
          "Senior Vice President",
          "Vice President",
          "Director",
          "Senior Manager",
          "Manager",
          "Senior Analyst",
          "Analyst",
          "Senior Consultant",
          "Consultant",
          "Senior Engineer",
          "Engineer",
          "Specialist",
          "Coordinator",
        ]),
        department: fakeValueFromList([
          "Executive",
          "Technology",
          "Finance",
          "Marketing",
          "Sales",
          "Operations",
          "Human Resources",
          "Legal",
          "Compliance",
          "Risk Management",
          "Product Management",
          "Customer Service",
          "Research and Development",
        ]),
        job_level: fakeValueFromList([
          "C_LEVEL",
          "VP_LEVEL",
          "DIRECTOR",
          "MANAGER",
          "SENIOR",
          "MID_LEVEL",
          "JUNIOR",
          "ENTRY_LEVEL",
        ]),
        employment_type: fakeValueFromList([
          "FULL_TIME",
          "PART_TIME",
          "CONTRACT",
          "TEMPORARY",
          "SEASONAL",
          "INTERN",
          "CONSULTANT",
        ]),
        annual_income: fakeMoneyAmountDecimal(7),
        monthly_income: fakeMoneyAmountDecimal(6),
        hourly_rate: fakeMoneyAmountDecimal(3),
        bonus_last_year: fakeMoneyAmountDecimal(6),
        stock_options_value: fakeMoneyAmountDecimal(7),
        benefits_value: fakeMoneyAmountDecimal(5),
        employment_start_date: fakeDateBeforeNow(
          20 * 365 * 24 * 60 * 60 * 1000
        ),
        years_with_employer: fakeNumberBounded(0, 35),
        years_in_industry: fakeNumberBounded(0, 45),
        years_in_position: fakeNumberBounded(0, 15),
        next_review_date: fakeDateAfterNow(180 * 24 * 60 * 60 * 1000),
        performance_rating: fakeValueFromList([
          "EXCEEDS_EXPECTATIONS",
          "MEETS_EXPECTATIONS",
          "BELOW_EXPECTATIONS",
          "OUTSTANDING",
          "SATISFACTORY",
          "NEEDS_IMPROVEMENT",
        ]),
        work_authorization: fakeValueFromList([
          "US_CITIZEN",
          "PERMANENT_RESIDENT",
          "H1B",
          "L1",
          "TN",
          "F1_OPT",
          "OTHER_VISA",
        ]),
        remote_work_eligible: fakeBoolean(),
        travel_required: fakeValueFromList([
          "NONE",
          "MINIMAL",
          "MODERATE",
          "EXTENSIVE",
          "INTERNATIONAL",
        ]),
        security_clearance: fakeValueFromList([
          "NONE",
          "CONFIDENTIAL",
          "SECRET",
          "TOP_SECRET",
          "TS_SCI",
        ]),
        work_address: {
          company_name: fakeCompanyName(),
          street_number: fakeNumberBounded(1, 999999),
          street_name: fakeStreetName(),
          suite: {
            $concat: ["Suite ", { $toString: fakeNumberBounded(100, 99999) }],
          },
          floor: fakeNumberBounded(1, 100),
          city: fakeTownName(),
          state: fakeValueFromList([
            "CA",
            "NY",
            "TX",
            "FL",
            "IL",
            "WA",
            "MA",
            "VA",
            "GA",
            "NC",
          ]),
          zip_code: fakeZipCode(),
          country: fakeCountryName(),
          phone: fakePaddedNumberAsText(10),
          extension: fakeNumber(4),
          email: fakeEmailAddress(20),
        },
        supervisor: {
          name: fakeFirstAndLastName(),
          title: fakeValueFromList([
            "Manager",
            "Director",
            "Vice President",
            "Senior Manager",
            "Team Lead",
          ]),
          phone: fakePaddedNumberAsText(10),
          email: fakeEmailAddress(15),
        },
        previous_employers: [
          {
            company_name: fakeCompanyName(),
            job_title: fakeValueFromList([
              "Senior Analyst",
              "Manager",
              "Director",
              "Consultant",
              "Specialist",
            ]),
            industry: fakeValueFromList([
              "Technology",
              "Finance",
              "Healthcare",
              "Manufacturing",
              "Retail",
            ]),
            start_date: fakeDateBeforeNow(25 * 365 * 24 * 60 * 60 * 1000),
            end_date: fakeDateBeforeNow(20 * 365 * 24 * 60 * 60 * 1000),
            annual_salary: fakeMoneyAmountDecimal(6),
            reason_for_leaving: fakeValueFromList([
              "CAREER_ADVANCEMENT",
              "RELOCATION",
              "LAYOFF",
              "BETTER_OPPORTUNITY",
              "COMPANY_CLOSURE",
              "PERSONAL_REASONS",
            ]),
            supervisor_name: fakeFirstAndLastName(),
            supervisor_phone: fakePaddedNumberAsText(10),
            eligible_for_rehire: fakeBoolean(),
            achievements: fakeListOfSubDocs(2, [
              "Increased sales by 25%",
              "Led team of 10 people",
              "Implemented new system",
              "Reduced costs by 15%",
              "Won company award",
            ]),
          },
          {
            company_name: fakeCompanyName(),
            job_title: fakeValueFromList([
              "Analyst",
              "Associate",
              "Coordinator",
              "Specialist",
              "Assistant",
            ]),
            industry: fakeValueFromList([
              "Finance",
              "Technology",
              "Healthcare",
              "Education",
              "Government",
            ]),
            start_date: fakeDateBeforeNow(30 * 365 * 24 * 60 * 60 * 1000),
            end_date: fakeDateBeforeNow(25 * 365 * 24 * 60 * 60 * 1000),
            annual_salary: fakeMoneyAmountDecimal(5),
            reason_for_leaving: fakeValueFromList([
              "CAREER_ADVANCEMENT",
              "EDUCATION",
              "RELOCATION",
              "BETTER_OPPORTUNITY",
            ]),
            supervisor_name: fakeFirstAndLastName(),
            supervisor_phone: fakePaddedNumberAsText(10),
            eligible_for_rehire: fakeBoolean(),
          },
          {
            company_name: fakeCompanyName(),
            job_title: fakeValueFromList([
              "Junior Analyst",
              "Assistant",
              "Intern",
              "Entry Level",
              "Trainee",
            ]),
            industry: fakeValueFromList([
              "Technology",
              "Finance",
              "Retail",
              "Manufacturing",
              "Services",
            ]),
            start_date: fakeDateBeforeNow(35 * 365 * 24 * 60 * 60 * 1000),
            end_date: fakeDateBeforeNow(30 * 365 * 24 * 60 * 60 * 1000),
            annual_salary: fakeMoneyAmountDecimal(4),
            reason_for_leaving: fakeValueFromList([
              "CAREER_ADVANCEMENT",
              "EDUCATION",
              "RELOCATION",
            ]),
            supervisor_name: fakeFirstAndLastName(),
            eligible_for_rehire: fakeBoolean(),
          },
        ],
        professional_certifications: [
          {
            certification_name: fakeValueFromList([
              "PMP",
              "CPA",
              "CFA",
              "FRM",
              "CISSP",
              "AWS Certified",
              "Google Cloud Certified",
              "Microsoft Certified",
            ]),
            issuing_organization: fakeCompanyName(),
            issue_date: fakeDateBeforeNow(3 * 365 * 24 * 60 * 60 * 1000),
            expiry_date: fakeDateAfterNow(2 * 365 * 24 * 60 * 60 * 1000),
            certification_number: fakePaddedNumberAsText(10),
            status: fakeValueFromList(["ACTIVE", "EXPIRED", "PENDING_RENEWAL"]),
          },
          {
            certification_name: fakeValueFromList([
              "Six Sigma",
              "Scrum Master",
              "ITIL",
              "Salesforce Certified",
              "Oracle Certified",
            ]),
            issuing_organization: fakeCompanyName(),
            issue_date: fakeDateBeforeNow(2 * 365 * 24 * 60 * 60 * 1000),
            expiry_date: fakeDateAfterNow(3 * 365 * 24 * 60 * 60 * 1000),
            certification_number: fakePaddedNumberAsText(10),
            status: fakeValueFromList(["ACTIVE", "EXPIRED", "PENDING_RENEWAL"]),
          },
        ],
        professional_memberships: fakeListOfSubDocs(3, [
          "American Management Association",
          "Project Management Institute",
          "Institute of Electrical and Electronics Engineers",
          "American Institute of CPAs",
          "CFA Institute",
          "Society for Human Resource Management",
        ]),
      },
    },
  },
];
